[build-system]
requires = [
    "setuptools == 70.1.0",
    "wheel ==0.43.0",
    "cython == 0.29.35",
    "scikit-build == 0.14.1",
    "cmake == 3.26.4",
    "setuptools_scm == 8.0.4"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = "tests"
timeout = "120"
